server:
  port: 8888
spring:
  datasource:
    username: group4
    password: CJMcjm136466!
    url: jdbc:mysql://test-group4.mysql.rds.aliyuncs.com:9988/group4_3?useunicode=true;&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
 mapper-locations: mapper/**/*Mapper.xml